name: Deploy spec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ljharb/actions/node/install@main
    - run: npm run build
    - name: commit changes
      uses: elstudio/actions-js-build/commit@v3
      with:
        commitMessage: "fixup: [spec] `npm run build`"
